version: '3.9'

services:
  activemq:
    image: apache/activemq-artemis:2.31.2
    container_name: activemq-local-dev
    ports:
      - "61616:61616"
      - "18161:8161"
    expose:
      - "61616"
      - "8161"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - ARTEMIS_USER=user
      - ARTEMIS_PASSWORD=pwd1234!
      - ANONYMOUS_LOGIN=false
      - TZ=Asia/Seoul
    networks:
      - active-q
    mem_limit: "256mb"
  producer:
    image: activemq-producer:v1
    container_name: activemq-local-producer
    build:
      context: ./producer
    ports:
      - "7071:7071"
    expose:
      - "7071"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - TZ=Asia/Seoul
    entrypoint: java -jar -Dspring.artemis.broker-url=tcp://activemq:61616 producer-0.0.1-SNAPSHOT.jar
    networks:
      - active-q
    mem_limit: "128mb"
    depends_on:
      - activemq
  consumer_1:
    image: activemq-consumer:v1
    container_name: activemq-local-consumer_1
    build:
      context: ./consumer
    ports:
      - "9099:9099"
    expose:
      - "9099"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - TZ=Asia/Seoul
    entrypoint: java -jar -Dspring.artemis.broker-url=tcp://activemq:61616 consumer-0.0.1-SNAPSHOT.jar
    networks:
      - active-q
    mem_limit: "128mb"
    depends_on:
      - activemq

networks:
  active-q:
    driver: bridge