server:
  port: 7071

spring:
  application:
    name: Producer for ActiveMQ
  artemis:
    broker-url: tcp://127.0.0.1:61616
    mode: native
    user: user
    password: pwd1234!

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus, health, info, metrics
  observations:
    key-values:
      application: ${spring.application.name}